### ISSUE TITLE
Not proper work of addon

### ISSUE THREAD

**Issue by ZakkHarov** [mariodavid/cuba-component-user-inbox#1]
In horizontal menu no indication about new messages. Messages don't mark as read after reading.

Cuba version 6.8.7

**Comment by ZakkHarov** [comment]
Hi, Mario.

Ok, waiting for 0.2.0. You are making very useful addon

Thank you.

Best regards, 
Sergey

**Comment by mariodavid** [comment]
Second request: done in #2.

**Comment by mariodavid** [comment]
First request: done in #3

**Comment by mariodavid** [comment]
I've released version 0.2.0 containing the changes you described.

You can find it here: https://bintray.com/mariodavid/cuba-components/cuba-component-user-inbox/0.2.0

thanks for participating.

Bye
Mario
