### ISSUE TITLE
A user without permission can create users in the system

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-user-inbox#11]
A common user without access to system users can create new users, permissions and roles since the list of users is not limited, allowing to go to the main user form.

![image](https://user-images.githubusercontent.com/22368175/42586765-7685da2a-84fe-11e8-989c-5456ba445340.png)

**Comment by mariodavid** [comment]
hi,

if it is possible or not to create users does not have anything to do with this app component. It will just open `sec$User.browse`. If you want to restrict what the user is allowed to do in this screen, you have to restrict it by a role. CUBAs best practices are to have a default role of type denying which means, that nothing that is allows is denied.

Bye
Mario
