### ISSUE TITLE
Ability to send messages to different users at the same time

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-user-inbox#12]
Ability to send messages to different users and / or all users of the system at the same time

**Comment by mariodavid** [comment]
hi,

this will be covered in the next 0.8.0 release. It is already implemented as part of #18

**Comment by mariodavid** [comment]
done in https://github.com/mariodavid/cuba-component-user-inbox/releases/tag/0.8.0. Thanks for the suggestion 👍
