### ISSUE TITLE
Request to have a New Message button on Browse and Edit screens

### ISSUE THREAD

**Issue by Zynde** [mariodavid/cuba-component-user-inbox#5]
Hey Mario,

It would be nice to have a button that appears in Browse and Edit screens to create a message with the Entity Link added. Maybe as a popup window.  I know you do this sort of thing in your other projects with the Attribute annotations.

What do you think?

**Comment by Zynde** [comment]
That would be super :)

**Comment by mariodavid** [comment]
done in #6 and released in https://github.com/mariodavid/cuba-component-user-inbox/releases/tag/0.3.0.

Thanks for your input.

bye
Mario

**Comment by Zynde** [comment]
Nice work. Thanks Mario
