### ISSUE TITLE
When Viewing a message you see the receiver and not the sender.

### ISSUE THREAD

**Issue by Zynde** [mariodavid/cuba-component-user-inbox#8]
Hi Mario,

It would be nice when viewing a message to be able to see the sender of the message.

It would also be very nice to be able to reply.

Is there a way of filtering the Users list in the send screen?

**Comment by mariodavid** [comment]
hi,

> It would be nice when viewing a message to be able to see the sender of the message.

thanks, will do. 

> It would also be very nice to be able to reply.

true :)

> Is there a way of filtering the Users list in the send screen?

There are two ways. You can do it via permissions. But this will be for the complete application then. You can also extend the screen and set the datasource query of the optionsDs.

**Comment by mariodavid** [comment]
done in 0.4.0. Thanks for mentioning
